openapi: 3.0.0
info:
  title: Recipes AI API
  version: 1.0.0
  description: API for Recipes AI service
paths:
  /health:
    get:
      summary: Health check endpoint
      description: Returns the status of the service
      operationId: getHealth
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [ok]
                  timestamp:
                    type: string
                    format: date-time
                required:
                  - status
                  - timestamp 